#!/usr/bin/env python3
"""Display settings panel for Hyprland, opened from the Waybar top bar.

Changes are applied live with `hyprctl eval` (this Hyprland is configured in Lua,
and its non-legacy parser refuses `hyprctl keyword`), verified against what the
compositor actually reports, and only then persisted to ~/.config/hypr/display.lua
(which hyprland.lua requires last, so these values win).

Resolution changes on a headless box are risky: the only way in is the Sunshine
stream, and a mode the client can't handle locks you out. So a mode/scale change
must be confirmed within REVERT_SECONDS or it is rolled back automatically -- if
the stream dies, doing nothing restores the previous mode.
"""

import json
import os
import re
import subprocess
import time
from math import gcd

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import GLib, Gtk  # noqa: E402

APP_ID = "dev.tunc.hypr-display-settings"

# GTK3 takes the Wayland app_id from the program name, NOT from Gtk.Application's
# application_id -- without this the class would be "display-settings.py" and the
# float rule in hyprland.lua would not match.
GLib.set_prgname(APP_ID)

HYPR_DIR = os.path.expanduser("~/.config/hypr")
GEN_LUA = os.path.join(HYPR_DIR, "display.lua")
CURSOR_THEME = os.environ.get("XCURSOR_THEME") or "default"

SCALE_MIN, SCALE_MAX = 1.0, 3.0
CURSOR_MIN, CURSOR_MAX = 12, 96
REVERT_SECONDS = 15

# Virtual outputs accept essentially any mode, and hyprctl's availableModes for
# them is NOT authoritative: HEADLESS-2 reports only 1920x1080@60 while happily
# running 2560x1440@120. Driving the dropdown off that list would offer exactly
# one wrong choice, so virtual outputs get this curated list instead. Physical
# outputs keep using the modes the display actually advertises.
PRESET_RES = [
    (1280, 720),
    (1600, 900),
    (1920, 1080),
    (2560, 1440),
    (3440, 1440),
    (3840, 2160),
]
PRESET_RATES = [60.0, 90.0, 120.0, 144.0, 165.0, 240.0]

MODE_RE = re.compile(r"^(\d+)x(\d+)@([\d.]+)Hz$")


def hyprctl(*args):
    """Run hyprctl; return (ok, output).

    hyprctl exits 0 even when it refuses a command (it just prints the reason),
    so for mutating calls `ok` must mean the reply was literally "ok".
    """
    try:
        r = subprocess.run(["hyprctl", *args], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, str(e)
    out = (r.stdout + r.stderr).strip()
    return r.returncode == 0 and out.lower() == "ok", out


def monitor_lua(name, mode, scale):
    return (
        f'hl.monitor({{ output = "{name}", mode = "{mode}", '
        f'position = "auto", scale = {fmt_scale(scale)} }})'
    )


def monitors():
    """Live monitor list. Reads JSON, so it can't use hyprctl()'s "ok" check."""
    try:
        r = subprocess.run(
            ["hyprctl", "-j", "monitors"], capture_output=True, text=True, timeout=10
        )
        return json.loads(r.stdout)
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return []


def is_virtual(m):
    return m["name"].upper().startswith("HEADLESS")


def available_modes(m):
    """(w, h, hz) tuples offerable for this monitor, best first.

    The live mode is always included: for a virtual output it is usually absent
    from availableModes, and it must stay selectable so "Apply" without touching
    resolution is a no-op rather than a surprise mode change.
    """
    if is_virtual(m):
        modes = [(w, h, r) for (w, h) in PRESET_RES for r in PRESET_RATES]
    else:
        modes = []
        for s in m.get("availableModes", []):
            hit = MODE_RE.match(s)
            if hit:
                modes.append((int(hit.group(1)), int(hit.group(2)), float(hit.group(3))))

    modes.append(current_mode(m))
    # dedupe, then widest -> highest refresh
    return sorted(set(modes), key=lambda t: (-(t[0] * t[1]), -t[2]))


def current_mode(m):
    return (m["width"], m["height"], round(float(m["refreshRate"]), 2))


def valid_scales(w, h):
    """Scales Hyprland will accept for a w*h panel.

    Hyprland snaps scale to 1/120 steps and rejects any scale that doesn't divide
    the mode into whole logical pixels. So scale = n/120 is valid only when
    n divides both w*120 and h*120, i.e. when n divides gcd(w*120, h*120).
    """
    g = gcd(w * 120, h * 120)
    lo, hi = int(SCALE_MIN * 120), int(SCALE_MAX * 120)
    return [n / 120 for n in range(lo, hi + 1) if g % n == 0]


def fmt_mode(w, h, hz):
    return f"{w}x{h}@{hz:.2f}"


def fmt_scale(s):
    return f"{s:g}"


def write_lua(rows, cursor_size):
    """Persist current selections. Written atomically."""
    lines = [
        "-- AUTOGENERATED by the Waybar display settings panel (top bar > the monitor icon).",
        "-- Manual edits here are overwritten. hyprland.lua requires this file last,",
        "-- so these values override the monitor blocks defined above it.",
        "",
    ]
    for name, mode, scale in rows:
        lines.append(monitor_lua(name, mode, scale))
    lines += [
        "",
        "-- Cursor size only affects apps launched after a Hyprland restart.",
        f'hl.env("XCURSOR_SIZE", "{cursor_size}")',
        f'hl.env("HYPRCURSOR_SIZE", "{cursor_size}")',
        "",
    ]
    tmp = GEN_LUA + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines))
    os.replace(tmp, GEN_LUA)


class MonitorRow:
    """Resolution / refresh / scale selectors for one monitor.

    Refresh and scale both depend on the chosen resolution (different modes
    expose different rates; valid scales are a function of w*h), so both are
    repopulated whenever resolution changes.
    """

    def __init__(self, m):
        self.mon = m
        self.modes = available_modes(m)
        self.prev = (fmt_mode(*current_mode(m)), round(float(m["scale"]), 6))

        cur_w, cur_h, cur_hz = current_mode(m)

        self.frame = Gtk.Frame(label=f"  {m['name']}  ")
        inner = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        inner.set_border_width(10)
        self.frame.add(inner)

        self.res = Gtk.ComboBoxText()
        self.resolutions = sorted(
            {(w, h) for w, h, _ in self.modes}, key=lambda t: -(t[0] * t[1])
        )
        for i, (w, h) in enumerate(self.resolutions):
            self.res.append_text(f"{w} x {h}")
            if (w, h) == (cur_w, cur_h):
                self.res.set_active(i)

        self.rate = Gtk.ComboBoxText()
        self.scale = Gtk.ComboBoxText()

        inner.pack_start(self._labelled("Resolution", self.res), False, False, 0)
        inner.pack_start(self._labelled("Refresh", self.rate), False, False, 0)
        inner.pack_start(self._labelled("Scale", self.scale), False, False, 0)

        self.logical = Gtk.Label(xalign=0)
        inner.pack_start(self.logical, False, False, 0)

        self._sync(cur_hz, round(float(m["scale"]), 6))
        self.res.connect("changed", lambda _c: self._sync())
        self.scale.connect("changed", lambda _c: self._show_logical())

        if is_virtual(m):
            note = Gtk.Label(xalign=0)
            note.set_markup(
                "<small>Virtual output: it accepts any mode, so this is a preset "
                "list rather than what the driver advertises. Match it to your "
                "Moonlight client for a 1:1 stream.</small>"
            )
            note.set_line_wrap(True)
            inner.pack_start(note, False, False, 0)

    @staticmethod
    def _labelled(text, widget):
        row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        lbl = Gtk.Label(label=text, xalign=0)
        lbl.set_size_request(80, -1)
        row.pack_start(lbl, False, False, 0)
        row.pack_start(widget, True, True, 0)
        return row

    def _sync(self, want_hz=None, want_scale=None):
        """Repopulate refresh + scale for the selected resolution."""
        w, h = self.selected_res()

        rates = sorted({hz for mw, mh, hz in self.modes if (mw, mh) == (w, h)}, reverse=True)
        self._rates = rates  # assign before populating; see the scale block below
        self.rate.remove_all()
        for hz in rates:
            self.rate.append_text(f"{hz:g} Hz")
        if want_hz is not None and rates:
            # Nearest, not highest: picking a resolution must never silently
            # change refresh (120 -> 240 would quietly desync the Moonlight
            # client). Exact match wins; otherwise land as close as we can.
            self.rate.set_active(min(range(len(rates)), key=lambda i: abs(rates[i] - want_hz)))
        if self.rate.get_active() < 0:
            self.rate.set_active(0)

        scales = valid_scales(w, h)
        # Compositor may sit on a scale our enumeration doesn't produce; keep it
        # selectable so Apply doesn't silently change it.
        odd = want_scale is not None and not any(abs(s - want_scale) < 1e-6 for s in scales)
        if odd:
            scales = scales + [want_scale]
        # Assign before populating: append_text/set_active below fire the combo's
        # "changed" handler, which reads self._scales. Assigning afterwards would
        # let it read the previous resolution's list.
        self._scales = scales

        self.scale.remove_all()
        for i, s in enumerate(scales):
            if odd and i == len(scales) - 1:
                self.scale.append_text(f"{fmt_scale(s)} (current, non-standard)")
            else:
                self.scale.append_text(f"{fmt_scale(s):<5}  ->  {int(w / s)}x{int(h / s)}")
            if want_scale is not None and abs(s - want_scale) < 1e-6:
                self.scale.set_active(i)
        if self.scale.get_active() < 0:
            self.scale.set_active(0)

        self._show_logical()

    def _show_logical(self):
        w, h = self.selected_res()
        s = self.selected_scale()
        if s:
            self.logical.set_markup(
                f"<small>Desktop renders {w}x{h}; apps see {int(w / s)}x{int(h / s)}."
                + ("" if s == 1 else "  Scale &gt; 1 makes XWayland apps blurry.")
                + "</small>"
            )

    def selected_res(self):
        return self.resolutions[max(self.res.get_active(), 0)]

    def selected_rate(self):
        return self._rates[max(self.rate.get_active(), 0)]

    def selected_scale(self):
        i = self.scale.get_active()
        return self._scales[i] if 0 <= i < len(self._scales) else None

    def target(self):
        w, h = self.selected_res()
        return (self.mon["name"], fmt_mode(w, h, self.selected_rate()), self.selected_scale())


class Panel(Gtk.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app, title="Display Settings")
        self.set_default_size(460, -1)
        self.set_resizable(False)
        self.set_border_width(0)

        outer = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.add(outer)

        self.set_titlebar(Gtk.HeaderBar(title="Display Settings", show_close_button=True))

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=14)
        box.set_border_width(16)
        outer.pack_start(box, True, True, 0)

        self.rows = []
        mons = monitors()
        if not mons:
            box.pack_start(Gtk.Label(label="No monitors reported by hyprctl."), False, False, 0)
        for m in mons:
            row = MonitorRow(m)
            self.rows.append(row)
            box.pack_start(row.frame, False, False, 0)

        box.pack_start(Gtk.Separator(), False, False, 0)

        crow = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        clabel = Gtk.Label(label="Cursor size", xalign=0)
        clabel.set_size_request(80, -1)
        crow.pack_start(clabel, False, False, 0)
        cur = min(max(int(os.environ.get("XCURSOR_SIZE") or 24), CURSOR_MIN), CURSOR_MAX)
        self.cursor = Gtk.SpinButton.new_with_range(CURSOR_MIN, CURSOR_MAX, 2)
        self.cursor.set_value(cur)
        crow.pack_start(self.cursor, True, True, 0)
        box.pack_start(crow, False, False, 0)

        note = Gtk.Label(xalign=0)
        note.set_markup(
            "<small>Resolution and scale apply instantly and must be confirmed. "
            "Cursor size applies to apps started afterwards.</small>"
        )
        note.set_line_wrap(True)
        box.pack_start(note, False, False, 0)

        self.status = Gtk.Label(xalign=0)
        self.status.set_line_wrap(True)
        box.pack_start(self.status, False, False, 0)

        btns = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        btns.set_halign(Gtk.Align.END)
        reset = Gtk.Button(label="Reset to config")
        reset.connect("clicked", self.on_reset)
        btns.pack_start(reset, False, False, 0)
        apply = Gtk.Button(label="Apply")
        apply.get_style_context().add_class("suggested-action")
        apply.connect("clicked", self.on_apply)
        btns.pack_start(apply, False, False, 0)
        box.pack_start(btns, False, False, 0)

    def _push(self, name, mode, scale):
        return hyprctl("eval", monitor_lua(name, mode, scale))

    def _matches(self, want):
        live = {
            m["name"]: (fmt_mode(*current_mode(m)), round(float(m["scale"]), 6))
            for m in monitors()
        }
        ok = all(
            n in live and live[n][0] == mode and abs(live[n][1] - scale) < 1e-3
            for n, mode, scale in want
        )
        return ok, live

    def _settled(self, want, timeout=4.0, hold=1.5):
        """Poll until the compositor reports `want` and HOLDS it, or give up.

        Two separate hazards:
        - Hyprland applies mode/scale asynchronously, so reading back immediately
          races and reports a false rejection. Hence polling rather than one read.
        - A mode can appear and then be dropped a moment later. Accepting the
          first match would persist a mode that never really ran, leaving
          display.lua describing a display that doesn't exist. Hence `hold`:
          the target must still be live after this long to count.
        """
        deadline = time.monotonic() + timeout
        while True:
            ok, live = self._matches(want)
            if ok:
                break
            if time.monotonic() > deadline:
                return False, live
            time.sleep(0.1)

        end = time.monotonic() + hold
        while time.monotonic() < end:
            time.sleep(0.25)
            ok, live = self._matches(want)
            if not ok:
                return False, live  # appeared, then fell back
        return True, live

    def on_apply(self, _btn):
        targets = [r.target() for r in self.rows if r.selected_scale()]
        changed = [t for t, r in zip(targets, self.rows) if (t[1], t[2]) != r.prev]

        size = int(self.cursor.get_value())
        hyprctl("setcursor", CURSOR_THEME, str(size))

        if not changed:
            write_lua(targets, size)
            self.status.set_markup('<span foreground="#26a65b">Saved.</span>')
            return

        failed = []
        for name, mode, scale in changed:
            ok, out = self._push(name, mode, scale)
            if not ok:
                failed.append(f"{name}: {out}")

        ok, live = self._settled([(n, m, s) for n, m, s in changed])
        if not ok:
            for name, mode, scale in changed:
                got = live.get(name)
                if not got or got[0] != mode or abs(got[1] - scale) > 1e-3:
                    failed.append(f"{name}: rejected (still at {got[0] if got else '?'})")

        if failed:
            self._revert()
            self.status.set_markup(
                '<span foreground="#cc0000">'
                + GLib.markup_escape_text("; ".join(failed))
                + "</span>"
            )
            return

        if self._confirm():
            write_lua(targets, size)
            for r, t in zip(self.rows, targets):
                r.prev = (t[1], t[2])
            self.status.set_markup('<span foreground="#26a65b">Applied and saved.</span>')
        else:
            self._revert()
            self.status.set_markup("Reverted; nothing saved.")

    def _revert(self):
        for r in self.rows:
            mode, scale = r.prev
            self._push(r.mon["name"], mode, scale)

    def _confirm(self):
        """Countdown dialog. Doing nothing reverts -- that is the point: if the
        new mode killed the stream, the user cannot click anything."""
        dlg = Gtk.MessageDialog(
            transient_for=self,
            modal=True,
            message_type=Gtk.MessageType.QUESTION,
            buttons=Gtk.ButtonsType.NONE,
            text="Keep these display settings?",
        )
        dlg.add_button("Revert", Gtk.ResponseType.CANCEL)
        keep = dlg.add_button("Keep", Gtk.ResponseType.OK)
        keep.get_style_context().add_class("suggested-action")
        dlg.set_default_response(Gtk.ResponseType.CANCEL)

        state = {"n": REVERT_SECONDS, "live": True}

        def label(n):
            dlg.format_secondary_text(f"Reverting in {n}s if you don't confirm.")

        label(state["n"])

        def tick():
            state["n"] -= 1
            if state["n"] <= 0:
                state["live"] = False
                dlg.response(Gtk.ResponseType.CANCEL)
                return False
            label(state["n"])
            return True

        src = GLib.timeout_add_seconds(1, tick)
        resp = dlg.run()
        if state["live"]:
            GLib.source_remove(src)
        dlg.destroy()
        return resp == Gtk.ResponseType.OK

    def on_reset(self, _btn):
        """Drop our overrides and let hyprland.lua's own values take over."""
        if os.path.exists(GEN_LUA):
            os.remove(GEN_LUA)
        ok, out = hyprctl("reload")
        if ok:
            self.status.set_markup(
                '<span foreground="#26a65b">Reset to hyprland.lua. Reopen to see values.</span>'
            )
        else:
            self.status.set_markup(
                '<span foreground="#cc0000">' + GLib.markup_escape_text(out) + "</span>"
            )


class App(Gtk.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID)

    def do_activate(self):
        win = Panel(self)
        win.show_all()
        win.present()


def toggle_guard():
    """Make the bar button a toggle: a second click closes the open panel.

    Done here rather than with `pkill -f` in the Waybar command, because that
    pattern also matches the shell running it, so the shell kills itself.
    Returns True if we should exit (we just closed a running panel).
    """
    run_dir = os.environ.get("XDG_RUNTIME_DIR") or "/tmp"
    pidfile = os.path.join(run_dir, "hypr-display-settings.pid")
    try:
        with open(pidfile) as f:
            old = int(f.read().strip())
        os.kill(old, 0)  # raises unless that pid is alive
    except (OSError, ValueError):
        pass  # stale or absent -> fall through and start
    else:
        try:
            os.kill(old, 15)
        except OSError:
            pass
        os.unlink(pidfile)
        return True

    with open(pidfile, "w") as f:
        f.write(str(os.getpid()))
    return False


if __name__ == "__main__":
    if toggle_guard():
        raise SystemExit(0)
    try:
        App().run(None)
    finally:
        run_dir = os.environ.get("XDG_RUNTIME_DIR") or "/tmp"
        try:
            os.unlink(os.path.join(run_dir, "hypr-display-settings.pid"))
        except OSError:
            pass
