#!/usr/bin/env python3
"""Display settings panel for Hyprland, opened from the Waybar top bar.

Changes are applied live with `hyprctl eval` (this Hyprland is configured in Lua,
and its non-legacy parser refuses `hyprctl keyword`), verified against what the
compositor actually reports, and only then persisted to ~/.config/hypr/display.lua
(which hyprland.lua requires last, so these values win).
"""

import json
import os
import subprocess
from math import gcd

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import GLib, Gtk  # noqa: E402

APP_ID = "dev.tunc.hypr-display-settings"

# GTK3 takes the Wayland app_id from the program name, NOT from Gtk.Application's
# application_id -- without this the class would be "display-settings.py" and the
# float rule in hyprland.lua would not match.
GLib.set_prgname(APP_ID)

HYPR_DIR = os.path.expanduser("~/.config/hypr")
GEN_LUA = os.path.join(HYPR_DIR, "display.lua")
CURSOR_THEME = os.environ.get("XCURSOR_THEME") or "default"

SCALE_MIN, SCALE_MAX = 1.0, 3.0
CURSOR_MIN, CURSOR_MAX = 12, 96


def hyprctl(*args):
    """Run hyprctl; return (ok, output).

    hyprctl exits 0 even when it refuses a command (it just prints the reason),
    so for mutating calls `ok` must mean the reply was literally "ok".
    """
    try:
        r = subprocess.run(["hyprctl", *args], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, str(e)
    out = (r.stdout + r.stderr).strip()
    return r.returncode == 0 and out.lower() == "ok", out


def monitor_lua(name, mode, scale):
    return (
        f'hl.monitor({{ output = "{name}", mode = "{mode}", '
        f'position = "auto", scale = {fmt_scale(scale)} }})'
    )


def monitors():
    """Live monitor list. Reads JSON, so it can't use hyprctl()'s "ok" check."""
    try:
        r = subprocess.run(
            ["hyprctl", "-j", "monitors"], capture_output=True, text=True, timeout=10
        )
        return json.loads(r.stdout)
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return []


def valid_scales(w, h):
    """Scales Hyprland will accept for a w*h panel.

    Hyprland snaps scale to 1/120 steps and rejects any scale that doesn't divide
    the mode into whole logical pixels. So scale = n/120 is valid only when
    n divides both w*120 and h*120, i.e. when n divides gcd(w*120, h*120).
    """
    g = gcd(w * 120, h * 120)
    lo, hi = int(SCALE_MIN * 120), int(SCALE_MAX * 120)
    return [n / 120 for n in range(lo, hi + 1) if g % n == 0]


def mode_of(m):
    return f"{m['width']}x{m['height']}@{m['refreshRate']:.2f}"


def fmt_scale(s):
    return f"{s:g}"


def write_lua(rows, cursor_size):
    """Persist current selections. Written atomically."""
    lines = [
        "-- AUTOGENERATED by the Waybar display settings panel (top bar > the monitor icon).",
        "-- Manual edits here are overwritten. hyprland.lua requires this file last,",
        "-- so these values override the monitor blocks defined above it.",
        "",
    ]
    for name, mode, scale in rows:
        lines.append(monitor_lua(name, mode, scale))
    lines += [
        "",
        "-- Cursor size only affects apps launched after a Hyprland restart.",
        f'hl.env("XCURSOR_SIZE", "{cursor_size}")',
        f'hl.env("HYPRCURSOR_SIZE", "{cursor_size}")',
        "",
    ]
    tmp = GEN_LUA + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines))
    os.replace(tmp, GEN_LUA)


class Panel(Gtk.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app, title="Display Settings")
        self.set_default_size(430, -1)
        self.set_resizable(False)
        self.set_border_width(0)

        outer = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.add(outer)

        header = Gtk.HeaderBar(title="Display Settings", show_close_button=True)
        self.set_titlebar(header)

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=14)
        box.set_border_width(16)
        outer.pack_start(box, True, True, 0)

        self.rows = []
        mons = monitors()

        if not mons:
            box.pack_start(Gtk.Label(label="No monitors reported by hyprctl."), False, False, 0)
        for m in mons:
            box.pack_start(self._monitor_frame(m), False, False, 0)

        box.pack_start(Gtk.Separator(), False, False, 0)

        # --- cursor size ---
        crow = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        clabel = Gtk.Label(label="Cursor size", xalign=0)
        clabel.set_size_request(90, -1)
        crow.pack_start(clabel, False, False, 0)

        cur = int(os.environ.get("XCURSOR_SIZE") or 24)
        cur = min(max(cur, CURSOR_MIN), CURSOR_MAX)
        self.cursor = Gtk.SpinButton.new_with_range(CURSOR_MIN, CURSOR_MAX, 2)
        self.cursor.set_value(cur)
        crow.pack_start(self.cursor, True, True, 0)
        box.pack_start(crow, False, False, 0)

        note = Gtk.Label(xalign=0)
        note.set_markup(
            '<small>Scale changes apply instantly. Cursor size applies to apps '
            'started afterwards.</small>'
        )
        note.set_line_wrap(True)
        box.pack_start(note, False, False, 0)

        # --- status ---
        self.status = Gtk.Label(xalign=0)
        self.status.set_line_wrap(True)
        box.pack_start(self.status, False, False, 0)

        # --- buttons ---
        btns = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
        btns.set_halign(Gtk.Align.END)
        reset = Gtk.Button(label="Reset to config")
        reset.connect("clicked", self.on_reset)
        btns.pack_start(reset, False, False, 0)
        apply = Gtk.Button(label="Apply")
        apply.get_style_context().add_class("suggested-action")
        apply.connect("clicked", self.on_apply)
        btns.pack_start(apply, False, False, 0)
        box.pack_start(btns, False, False, 0)

    def _monitor_frame(self, m):
        name, w, h = m["name"], m["width"], m["height"]
        frame = Gtk.Frame(label=f"  {name} — {w}x{h} @ {m['refreshRate']:.0f}Hz  ")
        inner = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        inner.set_border_width(10)
        frame.add(inner)

        scales = valid_scales(w, h)
        combo = Gtk.ComboBoxText()
        current = round(float(m["scale"]), 6)
        active = 0
        for i, s in enumerate(scales):
            combo.append_text(f"{fmt_scale(s):<6}  →  {int(w/s)}x{int(h/s)}")
            if abs(s - current) < 1e-6:
                active = i
        if not any(abs(s - current) < 1e-6 for s in scales):
            # Compositor is on a scale outside our enumerated range; show it.
            combo.append_text(f"{fmt_scale(current)} (current, non-standard)")
            scales = scales + [current]
            active = len(scales) - 1
        combo.set_active(active)

        row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        lbl = Gtk.Label(label="Scale", xalign=0)
        lbl.set_size_request(80, -1)
        row.pack_start(lbl, False, False, 0)
        row.pack_start(combo, True, True, 0)
        inner.pack_start(row, False, False, 0)

        self.rows.append({"mon": m, "combo": combo, "scales": scales})
        return frame

    def on_apply(self, _btn):
        applied, failed = [], []
        for r in self.rows:
            m, idx = r["mon"], r["combo"].get_active()
            if idx < 0:
                continue
            scale = r["scales"][idx]
            name, mode = m["name"], mode_of(m)
            # This Hyprland is configured in Lua, so `hyprctl keyword` is refused
            # ("keyword can't work with non-legacy parsers"). eval runs Lua instead.
            ok, out = hyprctl("eval", monitor_lua(name, mode, scale))
            if not ok:
                failed.append(f"{name}: {out}")
                continue
            applied.append((name, mode, scale))

        # Verify the compositor actually took the scale before persisting it.
        live = {m["name"]: round(float(m["scale"]), 6) for m in monitors()}
        confirmed = []
        for name, mode, scale in applied:
            if name in live and abs(live[name] - scale) < 1e-3:
                confirmed.append((name, mode, scale))
            else:
                failed.append(f"{name}: rejected (still at {live.get(name, '?')})")

        size = int(self.cursor.get_value())
        hyprctl("setcursor", CURSOR_THEME, str(size))

        if confirmed:
            write_lua(confirmed, size)

        if failed:
            self.status.set_markup(
                '<span foreground="#cc0000">' + GLib.markup_escape_text("; ".join(failed)) + "</span>"
            )
        else:
            self.status.set_markup('<span foreground="#26a65b">Applied and saved.</span>')

    def on_reset(self, _btn):
        """Drop our overrides and let hyprland.lua's own values take over."""
        if os.path.exists(GEN_LUA):
            os.remove(GEN_LUA)
        ok, out = hyprctl("reload")
        if ok:
            self.status.set_markup(
                '<span foreground="#26a65b">Reset to hyprland.lua. Reopen to see values.</span>'
            )
        else:
            self.status.set_markup('<span foreground="#cc0000">' + GLib.markup_escape_text(out) + "</span>")


class App(Gtk.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID)

    def do_activate(self):
        win = Panel(self)
        win.show_all()
        win.present()


def toggle_guard():
    """Make the bar button a toggle: a second click closes the open panel.

    Done here rather than with `pkill -f` in the Waybar command, because that
    pattern also matches the shell running it, so the shell kills itself.
    Returns True if we should exit (we just closed a running panel).
    """
    run_dir = os.environ.get("XDG_RUNTIME_DIR") or "/tmp"
    pidfile = os.path.join(run_dir, "hypr-display-settings.pid")
    try:
        with open(pidfile) as f:
            old = int(f.read().strip())
        os.kill(old, 0)  # raises unless that pid is alive
    except (OSError, ValueError):
        pass  # stale or absent -> fall through and start
    else:
        try:
            os.kill(old, 15)
        except OSError:
            pass
        os.unlink(pidfile)
        return True

    with open(pidfile, "w") as f:
        f.write(str(os.getpid()))
    return False


if __name__ == "__main__":
    if toggle_guard():
        raise SystemExit(0)
    try:
        App().run(None)
    finally:
        run_dir = os.environ.get("XDG_RUNTIME_DIR") or "/tmp"
        try:
            os.unlink(os.path.join(run_dir, "hypr-display-settings.pid"))
        except OSError:
            pass
