-- AUTOGENERATED by the Waybar display settings panel (top bar > the monitor icon).
-- Manual edits here are overwritten. hyprland.lua requires this file last,
-- so these values override the monitor blocks defined above it.

hl.monitor({ output = "HEADLESS-2", mode = "3840x2160@120.00", position = "auto", scale = 1.25 })

-- Cursor size only affects apps launched after a Hyprland restart.
hl.env("XCURSOR_SIZE", "22")
hl.env("HYPRCURSOR_SIZE", "22")
